# Generated by Django 5.2.3 on 2025-07-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie_persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('people', models.ManyToManyField(related_name='movies', through='movie_persons.MoviePerson', to='movie_persons.person')),
            ],
        ),
    ]
